
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  game_service:
    build: ./game_service
    ports:
      - "8000:80"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=aim_clicker
    depends_on:
      - mongodb

  leaderboard_service:
    build: ./leaderboard_service
    ports:
      - "8001:80"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=aim_clicker
    depends_on:
      - mongodb

  user_service:
    build: ./user_service
    ports:
      - "8002:80"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=aim_clicker
    depends_on:
      - mongodb

volumes:
  mongodb_data: